bash updates

diff --git a/bash/bash_functions b/bash/bash_functions
--- a/bash/bash_functions
+++ b/bash/bash_functions
@@ -10,6 +10,17 @@ mkdircd () {
 	mkdir -p "$@" && eval cd "\"\$$#\"";
 }
 
+# Make a temporary directory and enter it
+tmpd() {
+        local dir
+        if [ $# -eq 0 ]; then
+                dir=$(mktemp -d)
+        else
+                dir=$(mktemp -d -t "${1}.XXXXXXXXXX")
+        fi
+        cd "$dir" || exit
+}
+
 # Tar archive listing without untar
 tarls() {
 	 local file=${1}
@@ -200,3 +211,108 @@ transfer() {
     cat $tmpfile;
     rm -f $tmpfile;
 }
+
+# Create a data URL from a file
+dataurl() {
+        local mimeType
+        mimeType=$(file -b --mime-type "$1")
+        if [[ $mimeType == text/* ]]; then
+                mimeType="${mimeType};charset=utf-8"
+        fi
+        echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')"
+}
+
+# Create a git.io short URL
+gitio() {
+        if [ -z "${1}" ] || [ -z "${2}" ]; then
+                echo "Usage: \`gitio slug url\`"
+                return 1
+        fi
+        curl -i https://git.io/ -F "url=${2}" -F "code=${1}"
+}
+
+# Start an HTTP server from a directory, optionally specifying the port
+server() {
+        local port="${1:-8000}"
+        sleep 1 && open "http://localhost:${port}/" &
+        # Set the default Content-Type to `text/plain` instead of `application/octet-stream`
+        # And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
+        python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = "text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port"
+}
+
+# Compare original and gzipped file size
+comparegz() {
+        local origsize
+        origsize=$(wc -c < "$1")
+        local gzipsize
+        gzipsize=$(gzip -c "$1" | wc -c)
+        local ratio
+        ratio=$(echo "$gzipsize * 100 / $origsize" | bc -l)
+        printf "orig: %d bytes\n" "$origsize"
+        printf "gzip: %d bytes (%2.2f%%)\n" "$gzipsize" "$ratio"
+}
+
+# Syntax-highlight JSON strings or files
+# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
+json() {
+        if [ -t 0 ]; then # argument
+                python -mjson.tool <<< "$*" | pygmentize -l javascript
+        else # pipe
+                python -mjson.tool | pygmentize -l javascript
+        fi
+}
+
+# Run `dig` and display the most useful info
+digga() {
+        dig +nocmd "$1" any +multiline +noall +answer
+}
+
+# Show all the names (CNs and SANs) listed in the SSL certificate
+# for a given domain
+getcertnames() {
+        if [ -z "${1}" ]; then
+                echo "ERROR: No domain specified."
+                return 1
+        fi
+
+        local domain="${1}"
+        echo "Testing ${domain}…"
+        echo ""; # newline
+
+        local tmp
+        tmp=$(echo -e "GET / HTTP/1.0\nEOT" \
+                | openssl s_client -connect "${domain}:443" 2>&1)
+
+        if [[ "${tmp}" = *"-----BEGIN CERTIFICATE-----"* ]]; then
+                local certText
+                certText=$(echo "${tmp}" \
+                        | openssl x509 -text -certopt "no_header, no_serial, no_version, \
+                        no_signame, no_validity, no_issuer, no_pubkey, no_sigdump, no_aux")
+                echo "Common Name:"
+                echo ""; # newline
+                echo "${certText}" | grep "Subject:" | sed -e "s/^.*CN=//"
+                echo ""; # newline
+                echo "Subject Alternative Name(s):"
+                echo ""; # newline
+                echo "${certText}" | grep -A 1 "Subject Alternative Name:" \
+                        | sed -e "2s/DNS://g" -e "s/ //g" | tr "," "\n" | tail -n +2
+                return 0
+        else
+                echo "ERROR: Certificate not found."
+                return 1
+        fi
+}
+
+# `treee` is a longhand for `tree` with hidden files and color enabled, ignoring
+# the `.git` directory, listing directories first. The output gets piped into
+# `less` with options to preserve color and line numbers, unless the output is
+# small enough for one screen.
+treee() {
+        tree -aC -I '.git' --dirsfirst "$@" | less -FRNX
+}
+
+# gitignore.io
+function gitignore() { 
+        curl -L -s https://www.gitignore.io/api/$@ ;
+}
+
